version: "3.7"
services:
  dev-app:    # http://localhost:8000
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-app
    volumes:
      - ./src:/code
    ports:
      - '8000:8000'
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOST=localhost
      - DJANGO_DATABASE_ENGINE=django.db.backends.sqlite3
      - DJANGO_SECRET_KEY=development
#      - SLACK_TOKEN=secret
