# Generated by Django 4.1 on 2022-08-13 20:41

import bmd_core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotMyDeskUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slack_user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("email", models.EmailField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "access_token",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
            bases=(bmd_core.mixins.ModelUpdateMixin, models.Model),
        ),
    ]
