# Generated by Django 4.1.1 on 2022-10-06 18:36

import bmd_core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotMyDeskUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "next_background_run",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    "slack_user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("slack_email", models.EmailField(max_length=255)),
                ("slack_name", models.CharField(max_length=255)),
                ("slack_locale", models.CharField(max_length=16)),
                ("slack_tz", models.CharField(max_length=64)),
                ("next_slack_profile_update", models.DateTimeField(auto_now=True)),
                (
                    "bookmydesk_access_token",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "bookmydesk_access_token_expires_at",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "bookmydesk_refresh_token",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "preferred_notification_time_on_mondays",
                    models.TimeField(default=None, null=True),
                ),
                (
                    "preferred_notification_time_on_tuesdays",
                    models.TimeField(default=None, null=True),
                ),
                (
                    "preferred_notification_time_on_wednesdays",
                    models.TimeField(default=None, null=True),
                ),
                (
                    "preferred_notification_time_on_thursdays",
                    models.TimeField(default=None, null=True),
                ),
                (
                    "preferred_notification_time_on_fridays",
                    models.TimeField(default=None, null=True),
                ),
                (
                    "prefer_only_notifications_when_needed",
                    models.BooleanField(default=True),
                ),
            ],
            bases=(bmd_core.mixins.ModelUpdateMixin, models.Model),
        ),
    ]
