# Generated by Django 4.1 on 2022-08-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmd_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmydeskuser",
            name="locale",
            field=models.CharField(default="en-US", max_length=16),
            preserve_default=False,
        ),
    ]
