# Generated by Django 4.1 on 2022-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmd_core", "0002_user_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmydeskuser",
            name="next_profile_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
