# Generated by Django 4.1.2 on 2022-11-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmd_core", "0002_remove_botmydeskuser_slack_locale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botmydeskuser",
            name="next_background_run",
        ),
        migrations.AddField(
            model_name="botmydeskuser",
            name="last_notification_sent",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
