# Generated by Django 4.1.2 on 2022-11-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmd_core", "0003_remove_botmydeskuser_next_background_run_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmydeskuser",
            name="slack_tz",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
