# Generated by Django 4.1 on 2022-08-30 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmd_core", "0003_next_profile_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmydeskuser",
            name="notification_on_fridays",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="botmydeskuser",
            name="notification_on_mondays",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="botmydeskuser",
            name="notification_on_thursdays",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="botmydeskuser",
            name="notification_on_tuesdays",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="botmydeskuser",
            name="notification_on_wednesdays",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="botmydeskuser",
            name="notification_time",
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
    ]
